name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

env:
  GO_VERSION: '1.25.1'

jobs:
  test:
    name: Test & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Mage
        run: |
          git clone https://github.com/magefile/mage
          cd mage
          go run bootstrap.go
          cd ..
          rm -rf mage

      - name: Run checks (fmt, vet, test)
        run: mage check

  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para git describe funcionar

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Mage
        run: |
          git clone https://github.com/magefile/mage
          cd mage
          go run bootstrap.go
          cd ..
          rm -rf mage

      - name: Build all platforms
        run: mage build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gjg-launcher-binaries
          path: bin/*.exe
          retention-days: 1

      - name: Show build info
        run: |
          echo "### Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "| File | Size |" >> $GITHUB_STEP_SUMMARY
          echo "|------|------|" >> $GITHUB_STEP_SUMMARY
          for file in bin/*.exe; do
            size=$(du -h "$file" | cut -f1)
            name=$(basename "$file")
            echo "| $name | $size |" >> $GITHUB_STEP_SUMMARY
          done